trigger: none
pr: none

pool:
  name: Default  # ← Self-hosted Agent名にあわせて変更

variables:
  - name: System.Debug
    value: 'true'

stages:
- stage: TerraformAndNotify
  displayName: 'Terraform実行とSlack通知'
  jobs:
  - job: ApplyAndNotify
    displayName: 'RG作成 + Slack通知'
    steps:
    - task: PowerShell@2
      displayName: 'TerraformでRG作成'
      inputs:
        targetType: 'inline'
        script: |
          echo "=== 環境変数確認 ==="
          echo "CLIENT_ID: $env:ARM_CLIENT_ID"
          echo "TENANT_ID: $env:ARM_TENANT_ID"
          echo "SUBSCRIPTION_ID: $env:ARM_SUBSCRIPTION_ID"
          echo "CLIENT_SECRET: $env:ARM_CLIENT_SECRET"

          cd terraform
          terraform init

          # 一時ログファイルのパス
          $logFile = "$(System.DefaultWorkingDirectory)\tf_output.txt"

          # terraform apply 実行 + 出力をファイルにリダイレクト
          Start-Process -FilePath "terraform" `
                        -ArgumentList "apply -auto-approve" `
                        -RedirectStandardOutput $logFile `
                        -RedirectStandardError $logFile `
                        -NoNewWindow -Wait

          if ($LASTEXITCODE -eq 0) {
            echo "##vso[task.setvariable variable=TF_RESULT]success"
          } else {
            echo "##vso[task.setvariable variable=TF_RESULT]failed"
            exit 1
          }
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

    - task: PowerShell@2
      displayName: 'Slack通知（成功）'
      condition: and(succeeded(), eq(variables['TF_RESULT'], 'success'))
      inputs:
        targetType: 'inline'
        script: |
          $webhookUrl = $env:SLACK_WEBHOOK_URL
          if (-not $webhookUrl) {
            Write-Error "❌ SLACK_WEBHOOK_URL が空です。Pipeline の変数を確認してください。"
            exit 1
          }

          $payload = @{ text = "✅ リソースグループ作成が完了しました（terraform apply）✅" } | ConvertTo-Json -Compress
          $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
          $body = $utf8NoBom.GetBytes($payload)

          Invoke-RestMethod -Uri $webhookUrl -Method POST -Body $body -ContentType 'application/json'
      env:
        SLACK_WEBHOOK_URL: $(SLACK_WEBHOOK_URL)

    - task: PowerShell@2
      displayName: 'Slack通知（失敗）'
      condition: failed()
      inputs:
        targetType: 'inline'
        script: |
          $webhookUrl = $env:SLACK_WEBHOOK_URL
          if (-not $webhookUrl) {
            Write-Error "❌ SLACK_WEBHOOK_URL が空です。Pipeline の変数を確認してください。"
            exit 1
          }

          $tfOutputFile = "$(System.DefaultWorkingDirectory)\tf_output.txt"
          if (Test-Path $tfOutputFile) {
            $output = Get-Content $tfOutputFile -Raw
            $shortOutput = $output.Substring(0, [Math]::Min(500, $output.Length))
          } else {
            $shortOutput = "出力ファイルが見つかりませんでした。"
          }

          $payload = @{
            text = "❌ リソースグループ作成に失敗しました（terraform apply）"
            attachments = @(
              @{
                color = "danger"
                text = "```$shortOutput```"
              }
            )
          } | ConvertTo-Json -Depth 10 -Compress

          $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
          $body = $utf8NoBom.GetBytes($payload)

          Invoke-RestMethod -Uri $webhookUrl -Method POST -Body $body -ContentType 'application/json'
      env:
        SLACK_WEBHOOK_URL: $(SLACK_WEBHOOK_URL)
