trigger: none
pr: none

pool:
  name: Default  # Self-hosted Agent名に合わせて変更

variables:
  - name: System.Debug
    value: 'true'

stages:
- stage: TerraformAndNotify
  displayName: 'Terraform実行とSlack通知'
  jobs:
  - job: ApplyAndNotify
    displayName: 'RG作成 + Slack通知'
    steps:
    - task: PowerShell@2
      displayName: 'TerraformでRG作成'
      inputs:
        targetType: 'inline'
        script: |
          echo "=== 環境変数確認 ==="
          echo "CLIENT_ID: $env:ARM_CLIENT_ID"
          echo "TENANT_ID: $env:ARM_TENANT_ID"
          echo "SUBSCRIPTION_ID: $env:ARM_SUBSCRIPTION_ID"
          echo "CLIENT_SECRET: $env:ARM_CLIENT_SECRET"

          cd terraform
          terraform init
          terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

    # 成功時のSlack通知
    - task: PowerShell@2
      displayName: 'Slack通知（成功）'
      condition: succeeded()
      inputs:
        targetType: 'inline'
        script: |
          $webhookUrl = $env:SLACK_WEBHOOK_URL
          if (-not $webhookUrl) {
            Write-Error "❌ SLACK_WEBHOOK_URL が空です。Pipeline の変数を確認してください。"
            exit 1
          }

          $message = @{ text = "✅ リソースグループ作成完了（terraform apply）" } | ConvertTo-Json -Compress
          $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
          $body = $utf8NoBom.GetBytes($message)

          Invoke-RestMethod -Uri $webhookUrl -Method POST -Body $body -ContentType 'application/json'

    # 失敗時のSlack通知
    - task: PowerShell@2
      displayName: 'Slack通知（失敗）'
      condition: failed()
      inputs:
        targetType: 'inline'
        script: |
          $webhookUrl = $env:SLACK_WEBHOOK_URL
          if (-not $webhookUrl) {
            Write-Error "❌ SLACK_WEBHOOK_URL が空です。Pipeline の変数を確認してください。"
            exit 1
          }

          $message = @{ text = "❌ リソースグループ作成に失敗しました（terraform apply）" } | ConvertTo-Json -Compress
          $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
          $body = $utf8NoBom.GetBytes($message)

          Invoke-RestMethod -Uri $webhookUrl -Method POST -Body $body -ContentType 'application/json'
      env:
        SLACK_WEBHOOK_URL: $(SLACK_WEBHOOK_URL)
