trigger: none
pr: none

pool:
  name: Default  # ← Self-hosted Agent名にあわせて変更

variables:
  - name: System.Debug
    value: 'true'

stages:
- stage: TerraformAndNotify
  displayName: 'Terraform実行とSlack通知'
  jobs:
  - job: ApplyAndNotify
    displayName: 'RG作成 + Slack通知'
    steps:
    - task: PowerShell@2
      displayName: 'TerraformでRG作成'
      inputs:
        targetType: 'inline'
        script: |
          echo "=== 環境変数確認 ==="
          echo "CLIENT_ID: $env:ARM_CLIENT_ID"
          echo "TENANT_ID: $env:ARM_TENANT_ID"
          echo "SUBSCRIPTION_ID: $env:ARM_SUBSCRIPTION_ID"
          echo "CLIENT_SECRET: $env:ARM_CLIENT_SECRET"

          cd terraform
          terraform init

          # terraform apply の結果をキャプチャ
          $output = terraform apply -auto-approve 2>&1
          $exitCode = $LASTEXITCODE

          # 出力を環境変数に保存（失敗時用）
          $escaped = $output -replace "`r`n", "\n" -replace "`n", "\n" -replace "`r", ""
          $truncated = $escaped.Substring(0, [Math]::Min(500, $escaped.Length))
          Write-Host "##vso[task.setvariable variable=TF_ERROR_OUTPUT]$truncated"

          if ($exitCode -eq 0) {
            Write-Host "##vso[task.setvariable variable=TF_RESULT]success"
          } else {
            Write-Host "##vso[task.setvariable variable=TF_RESULT]failed"
            exit 1
          }
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

    - task: PowerShell@2
      displayName: 'Slack通知（成功）'
      condition: and(succeeded(), eq(variables['TF_RESULT'], 'success'))
      inputs:
        targetType: 'inline'
        script: |
          $webhookUrl = $env:SLACK_WEBHOOK_URL
          if (-not $webhookUrl) {
            Write-Error "❌ SLACK_WEBHOOK_URL が空です。Pipeline の変数を確認してください。"
            exit 1
          }

          $payload = @{ text = "✅ リソースグループ作成が完了しました（terraform apply）✅" } | ConvertTo-Json -Compress
          $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
          $body = $utf8NoBom.GetBytes($payload)

          Invoke-RestMethod -Uri $webhookUrl -Method POST -Body $body -ContentType 'application/json'
      env:
        SLACK_WEBHOOK_URL: $(SLACK_WEBHOOK_URL)

    - task: PowerShell@2
      displayName: 'Slack通知（失敗）'
      condition: failed()
      inputs:
        targetType: 'inline'
        script: |
          $webhookUrl = $env:SLACK_WEBHOOK_URL
          if (-not $webhookUrl) {
            Write-Error "❌ SLACK_WEBHOOK_URL が空です。Pipeline の変数を確認してください。"
            exit 1
          }

          $errorOutput = "$(TF_ERROR_OUTPUT)"
          if (-not $errorOutput) {
            $errorOutput = "エラー出力が取得できませんでした。"
          }

          $payload = @{
            text = "❌ リソースグループ作成に失敗しました（terraform apply）"
            attachments = @(
              @{
                color = "danger"
                text = "```$errorOutput```"
              }
            )
          } | ConvertTo-Json -Depth 10 -Compress

          $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
          $body = $utf8NoBom.GetBytes($payload)

          Invoke-RestMethod -Uri $webhookUrl -Method POST -Body $body -ContentType 'application/json'
      env:
        SLACK_WEBHOOK_URL: $(SLACK_WEBHOOK_URL)
